name: Rust

on:
  push:
    branches: [ master, test_downstream ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare dependencies
      run: sudo apt-get install coinor-libcbc-dev
    - name: Build
      run: cargo build --verbose --all
    - name: Run tests
      run: cargo test --verbose --all
  
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare dependencies
      shell: powershell
      run: |
          Install-Module 7Zip4PowerShell -Force -Verbose
          mkdir C:\Cbc
          Invoke-WebRequest "https://bintray.com/coin-or/download/download_file?file_path=Cbc-2.10-win64-msvc14-md.zip" -OutFile "C:\Cbc\Cbc-2.9.zip"
          Invoke-WebRequest "https://bintray.com/coin-or/download/download_file?file_path=Clp-1.17-win64-msvc14-mdd.zip" -OutFile "C:\Cbc\Clp-1.17.zip"
          7z x C:\Cbc\Cbc-2.9.zip -o"C:\Cbc\"
          7z x C:\Cbc\Clp-1.17.zip -o"C:\Clp\"
          Get-ChildItem -Path "C:\Cbc"
          Get-ChildItem -Path "C:\Cbc\lib"
          Get-ChildItem -Path "C:\Clp"
          Get-ChildItem -Path "C:\Clp\lib"
          echo "C:\Cbc\lib" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Clp\lib" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo $env:GITHUB_PATH
          type $env:GITHUB_PATH
    - name: Build
      run: cargo build --verbose --all
    - name: Run tests
      run: cargo test --verbose --all
